/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import archivos.Datos;
import archivos.Guardar;
import control.ControlUsuarios;
import control.Formato;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author emgl_
 */
public class AdministrarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarUsuarios
     */
    public AdministrarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraNavegacion = new javax.swing.JPanel();
        btnVerUsuarios = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnAgregarUsuario1 = new javax.swing.JButton();
        verUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        agregarUsuarios = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoClave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        campoClaveRepetida = new javax.swing.JPasswordField();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labelEspacioAsignado = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        campoUsuario = new javax.swing.JTextField();
        campoMedida = new javax.swing.JComboBox<>();
        campoRuta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        campoEspacio = new JFormattedTextField (new Integer(0));
        labelClaveCorta = new javax.swing.JLabel();
        labelUsuarioDisponible = new javax.swing.JLabel();
        labelClaveDiferente = new javax.swing.JLabel();

        setTitle("Administrar Usuarios | Cloud Network");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraNavegacion.setBackground(new java.awt.Color(67, 137, 186));
        barraNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerUsuarios.setText("Ver Usuarios\n");
        btnVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuariosActionPerformed(evt);
            }
        });
        barraNavegacion.add(btnVerUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        barraNavegacion.add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        btnAgregarUsuario1.setText("Modificar Usuario");
        btnAgregarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuario1ActionPerformed(evt);
            }
        });
        barraNavegacion.add(btnAgregarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        getContentPane().add(barraNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        verUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        verUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarios.setModel(control.ControlUsuarios.actualizarModelo());
        tablaUsuarios.setEnabled(false);
        jScrollPane1.setViewportView(tablaUsuarios);

        verUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 27, 760, 420));

        getContentPane().add(verUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        agregarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        agregarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        agregarUsuarios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        agregarUsuarios.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 730, 30));

        jLabel3.setText("Usuario:");
        agregarUsuarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setText("Dirección de Carpeta:");
        agregarUsuarios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        campoClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoClaveFocusLost(evt);
            }
        });
        agregarUsuarios.add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 310, 30));

        jLabel5.setText("Repita la clave:");
        agregarUsuarios.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        campoClaveRepetida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoClaveRepetidaFocusLost(evt);
            }
        });
        agregarUsuarios.add(campoClaveRepetida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 280, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        agregarUsuarios.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 80, 30));

        jLabel7.setText("Clave:");
        agregarUsuarios.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        labelEspacioAsignado.setText("Espacio para asignar:");
        agregarUsuarios.add(labelEspacioAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jButton8.setText("Registrar Usuario");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        agregarUsuarios.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 210, 40));

        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusLost(evt);
            }
        });
        agregarUsuarios.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 310, 30));

        campoMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bytes", "KB", "MB", "GB", "TB" }));
        agregarUsuarios.add(campoMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 90, 30));

        campoRuta.setEnabled(false);
        agregarUsuarios.add(campoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 630, 30));

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        agregarUsuarios.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 80, 30));

        campoEspacio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarUsuarios.add(campoEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 210, 30));

        labelClaveCorta.setForeground(new java.awt.Color(204, 0, 0));
        agregarUsuarios.add(labelClaveCorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 270, 20));

        labelUsuarioDisponible.setForeground(new java.awt.Color(204, 0, 0));
        agregarUsuarios.add(labelUsuarioDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 380, 30));

        labelClaveDiferente.setForeground(new java.awt.Color(204, 0, 0));
        agregarUsuarios.add(labelClaveDiferente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 190, 20));

        getContentPane().add(agregarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuariosActionPerformed
        tablaUsuarios.setModel(ControlUsuarios.actualizarModelo());
        verUsuarios.setVisible(true);
        agregarUsuarios.setVisible(false);
        
    }//GEN-LAST:event_btnVerUsuariosActionPerformed

    
    
    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        verUsuarios.setVisible(false);
        agregarUsuarios.setVisible(true);
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnAgregarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarUsuario1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JFileChooser selectorCarpeta = new JFileChooser();
        selectorCarpeta.setDialogTitle("Seleccione la carpeta para guardar los datos del usuario");
        selectorCarpeta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        selectorCarpeta.setAcceptAllFileFilterUsed(false);
        if(JFileChooser.APPROVE_OPTION==selectorCarpeta.showOpenDialog(this)){
            File carpetaSeleccionada = selectorCarpeta.getSelectedFile();
            campoRuta.setText(carpetaSeleccionada.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jButton1.getText().equals("Ver")){
            jButton1.setText("Ocultar");
            campoClave.setEchoChar((char)0);
            campoClaveRepetida.setEchoChar((char)0);
        }else{
            jButton1.setText("Ver");
            campoClave.setEchoChar('*');
            campoClaveRepetida.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusLost
        if(ControlUsuarios.existeUsuario(campoUsuario.getText())){
           labelUsuarioDisponible.setText("*El usuario ya se encuentra siendo utilizado."); 
        }else{
           labelUsuarioDisponible.setText("");  
        }
            
    }//GEN-LAST:event_campoUsuarioFocusLost

    private void campoClaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoClaveFocusLost
        if(Formato.validarClave(campoClave.getText())){
            labelClaveCorta.setText("");
        }else{
            labelClaveCorta.setText("La clave debe tener 6 caracteres como mínimo.");
        }
        if(campoClave.getText().equals(campoClaveRepetida.getText())){
            labelClaveDiferente.setText("");
        }else{
            labelClaveDiferente.setText("Las claves no coinciden.");
        }
    }//GEN-LAST:event_campoClaveFocusLost

    private void campoClaveRepetidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoClaveRepetidaFocusLost
        if(campoClave.getText().equals(campoClaveRepetida.getText())){
            labelClaveDiferente.setText("");
        }else{
            labelClaveDiferente.setText("Las claves no coinciden.");
        }
    }//GEN-LAST:event_campoClaveRepetidaFocusLost

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(labelUsuarioDisponible.getText().equals("") && labelClaveCorta.getText().equals("") && labelClaveDiferente.getText().equals("")){
            Usuario usuario = new Usuario();
            usuario.setUsuario(campoUsuario.getText());
            usuario.setClave(campoClave.getText());
            usuario.setNombre(campoNombre.getText());
            usuario.setEsAdministrador(false);
            usuario.setRuta(campoRuta.getText());
            
            switch ((String)campoMedida.getSelectedItem()){
                case "Bytes":{
                    usuario.setEspacioAsignado(Double.parseDouble(campoEspacio.getText())/1000000);
                    break;
                }
                case "KB":{
                    usuario.setEspacioAsignado(Double.parseDouble(campoEspacio.getText())/1000);
                    break;
                }
                case "MB":{
                    usuario.setEspacioAsignado(Double.parseDouble(campoEspacio.getText()));
                    break;
                }
                case "GB":{
                    usuario.setEspacioAsignado(Double.parseDouble(campoEspacio.getText())*1000);
                    break;
                }
                case "TB":{
                    usuario.setEspacioAsignado(Double.parseDouble(campoEspacio.getText())*1000000);
                    break;
                }
            }
            Datos.agregarUsuario(usuario);
            Guardar.enJSON();
            JOptionPane.showMessageDialog(this, "Usuario registrado satisfactoriamente.");
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarUsuarios;
    private javax.swing.JPanel barraNavegacion;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnAgregarUsuario1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVerUsuarios;
    private javax.swing.JPasswordField campoClave;
    private javax.swing.JPasswordField campoClaveRepetida;
    private javax.swing.JFormattedTextField campoEspacio;
    private javax.swing.JComboBox<String> campoMedida;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelClaveCorta;
    private javax.swing.JLabel labelClaveDiferente;
    private javax.swing.JLabel labelEspacioAsignado;
    private javax.swing.JLabel labelUsuarioDisponible;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JPanel verUsuarios;
    // End of variables declaration//GEN-END:variables
}
