/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import control.ControlUsuarios;

/**
 *
 * @author emgl_
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        tituloDeVentana = new javax.swing.JLabel();
        campoClave = new javax.swing.JPasswordField();
        campoUsuario = new javax.swing.JTextField();
        tituloUsuario = new javax.swing.JLabel();
        tituloUsuario1 = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelRegistrate = new javax.swing.JLabel();
        registro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cloud Network");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setBackground(new java.awt.Color(44, 90, 122));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 600));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloDeVentana.setBackground(new java.awt.Color(255, 255, 255));
        tituloDeVentana.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tituloDeVentana.setForeground(new java.awt.Color(21, 43, 59));
        tituloDeVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDeVentana.setText("INICIO DE SESIÓN");
        login.add(tituloDeVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 399, -1));

        campoClave.setToolTipText("Ingrese su contraseña.");
        login.add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 320, 30));

        campoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        campoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        campoUsuario.setToolTipText("Ingrese su usuario.");
        login.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 320, 30));

        tituloUsuario.setText("Usuario:");
        login.add(tituloUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        tituloUsuario1.setText("Contraseña:");
        login.add(tituloUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        login.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 130, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("¿Primera vez en Cloud Network?");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        labelRegistrate.setForeground(new java.awt.Color(102, 102, 102));
        labelRegistrate.setText("Regístrate aquí");
        labelRegistrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegistrateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegistrateMouseExited(evt);
            }
        });
        login.add(labelRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 460, 600));

        registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 460, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        if(ControlUsuarios.validarClave(campoUsuario.getText(),campoClave.getText())){
            InicioServidor inicio = new InicioServidor(ControlUsuarios.buscarUsuario(campoUsuario.getText()));
            inicio.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void labelRegistrateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrateMouseEntered
        labelRegistrate.setForeground(new java.awt.Color(67, 137, 186));
    }//GEN-LAST:event_labelRegistrateMouseEntered

    private void labelRegistrateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrateMouseExited
        labelRegistrate.setForeground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_labelRegistrateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPasswordField campoClave;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelRegistrate;
    private javax.swing.JPanel login;
    private javax.swing.JPanel registro;
    private javax.swing.JLabel tituloDeVentana;
    private javax.swing.JLabel tituloUsuario;
    private javax.swing.JLabel tituloUsuario1;
    // End of variables declaration//GEN-END:variables
}
